name: Build Windows One-Click EXE

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m venv venv
          venv\Scripts\pip install --upgrade pip
          venv\Scripts\pip install streamlit networkx matplotlib pyinstaller

      - name: Build C++ exe
        run: |
          cmake -S src/ostovost_task -B build_cpp -G "Visual Studio 17 2022" -A x64
          cmake --build build_cpp --config Release
          echo.
          echo Ищем ostov_task.exe...
          dir build_cpp /s /b | findstr ostov_task.exe
          for /r build_cpp %%f in (ostov_task.exe) do copy "%%f" src\ostov_task.exe
          if not exist src\ostov_task.exe (
            echo [ERROR] C++ exe не найден!
            exit 1
          )
          echo C++ exe успешно скопирован!

      - name: Build final single EXE
        run: |
          venv\Scripts\pyinstaller --onefile ^
                               --add-data "src;src" ^
                               --name "Остов с максимум листьев" ^
                               --windowed ^
                               src/main.py

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Один-клик
          path: |
            dist/Остов с максимум листьев.exe
            src/ostov_task.exe